; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;

;80:F1:B2:D2:BC:93-if00 -> ../../ttyACM1

[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4-evboard

framework = espidf

monitor_speed = 115200
upload_protocol = esptool

board_build.esp-idf.enable_component_manager = true