#ifndef Metric_Events_h
#define Metric_Events_h

#include <stdint.h>
#include <time.h>

#include "models.h"

#define IS_24_HR_LOW 0x0001
#define IS_24_HR_HIGH 0x0002

#define TS_IS_VALID ((uint16_t)0xA005) // All ts values are of the form 101xxxxxxxxxx101
#define TS_NO_VALUE ((uint16_t)0x0010)

typedef enum : uint16_t
{
    METRIC_INSIDE_BME280_TEMPERATURE,
    METRIC_INSIDE_BME280_HUMIDITY,
    METRIC_INSIDE_BME280_PRESSURE,
    METRIC_INSIDE_SGP30_ECO2,
    METRIC_INSIDE_SGP30_TVOC,
    METRIC_INSIDE_SGP30_AQI,
    METRIC_OUTSIDE1_BME280_TEMPERATURE,
    METRIC_OUTSIDE1_BME280_HUMIDITY,
    METRIC_OUTSIDE1_BME280_PRESSURE,
    METRIC_OUTSIDE1_BME280_BATTERY,
    METRIC_OUTSIDE_UV_RAW,
    METRIC_OUTSIDE_UV_INDEX,
    METRIC_OUTSIDE_UV_BATTERY,
    METRIC_OUTSIDE_SPS30_PM1P0MASS,
    METRIC_OUTSIDE_SPS30_PM2P5MASS,
    METRIC_OUTSIDE_SPS30_PM4P0MASS,
    METRIC_OUTSIDE_SPS30_PM10MASS,
    METRIC_OUTSIDE_SPS30_PM0P5NUMBER,
    METRIC_OUTSIDE_SPS30_PM1P0NUMBER,
    METRIC_OUTSIDE_SPS30_PM2P5NUMBER,
    METRIC_OUTSIDE_SPS30_PM4P0NUMBER,
    METRIC_OUTSIDE_SPS30_PM10NUMBER,
    METRIC_OUTSIDE_SPS30_BATTERY,
    METRIC_OUTSIDE_RAINFULL_TICKS,
    METRIC_OUTSIDE_RAINFULL_MM_HOUR,
    METRIC_OUTSIDE_RAINFULL_MM_6HOURS,
    METRIC_OUTSIDE_RAINFULL_MM_12HOURS,
    METRIC_OUTSIDE_RAINFULL_MM_24HOURS,
    METRIC_OUTSIDE_RAINFULL_BATTERY,
    METRIC_SPARE_1,
    METRIC_SPARE_2,
    METRIC_SPARE_3,
    METRIC_SPARE_4,
    METRIC_SPARE_5,
    METRIC_SPARE_6,
    METRIC_SPARE_7,
    METRIC_SPARE_8,
    METRIC_SPARE_9,
    METRIC_SPARE_10,
    METRIC_SPARE_11,
    METRIC_COUNT
} metric_id_t;

typedef struct
{
    time_t timestamp;
    sensor_id_t sensor_id;
    metric_id_t metric_id;
    uint16_t time_series_attributes;
    float max;
    float min;
    float average;
} __attribute__((packed)) timeseries_data_t;

typedef struct
{
    metric_id_t metric_id;
    uint16_t attributes;
    float value;
} metric_event_t;

#endif